"""
``--autogenerate`` must not propose dropping tables this app does not own.

The regression this pins is in the repo's history. ``cf552df2d140``, generated
with ``alembic revision --autogenerate`` and committed under the name "added in
ads model selected_account_id", also contained::

    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_table('checkpoint_blobs')
    op.drop_table('checkpoints')
    op.drop_column('campaigns', 'publish_state')

The four tables belong to LangGraph's ``AsyncPostgresSaver``, which creates them
itself and never declares them in ``Base.metadata`` — so autogenerate reads them
as orphans. Dropping them destroys every in-flight conversation. The column is
the publish ledger, and a database at head had no such column until
``d9e4a17c85b3`` put it back, meaning ``save_publish_state`` raised
``UndefinedColumnError`` on every publish.
"""
from __future__ import annotations

from types import SimpleNamespace

import pytest

from app.db.autogen_filters import LANGGRAPH_TABLES, include_object
from app.modules.campaigns.models import Campaign


@pytest.mark.parametrize("name", sorted(LANGGRAPH_TABLES))
def test_langgraph_tables_are_never_autogenerated_against(name):
    assert include_object(None, name, "table", True, None) is False


@pytest.mark.parametrize("name", sorted(LANGGRAPH_TABLES))
def test_indexes_on_those_tables_are_skipped_too(name):
    """cf552df2d140 dropped the indexes as well as the tables."""
    index = SimpleNamespace(table=SimpleNamespace(name=name))
    assert include_object(index, f"{name}_thread_id_idx", "index", True, None) is False


def test_our_own_tables_still_get_autogenerated():
    """A filter that excluded too much would silently stop generating migrations
    for real model changes — a slower version of the same problem."""
    for name in ("campaigns", "oauth_tokens", "users"):
        assert include_object(None, name, "table", True, None) is True
    index = SimpleNamespace(table=SimpleNamespace(name="campaigns"))
    assert include_object(index, "ix_campaigns_user_id", "index", True, None) is True


def test_publish_state_is_declared_on_the_model():
    """The column autogenerate dropped. If it leaves the model again, the next
    autogenerate run will propose dropping it from the database again."""
    assert "publish_state" in Campaign.__table__.columns


def test_migrations_have_exactly_one_head():
    """Two heads make `alembic upgrade head` abort and apply NOTHING, silently —
    the app then runs against a schema older than its models. That shipped once:
    two migration branches both parented on a93a65af1cb4 left `purged_at` /
    `updated_at` / `suppressed_maids` missing in every environment that ran
    `alembic upgrade head`, and every MAID extraction failed at the DB insert."""
    from alembic.config import Config
    from alembic.script import ScriptDirectory

    heads = ScriptDirectory.from_config(Config("alembic.ini")).get_heads()
    assert len(heads) == 1, f"multiple alembic heads: {heads}"
