"""Conversion tracking is keyed by ad account, not by login.

Two regressions pinned here, both of which shipped:

1. The four ``tracking_*`` columns sat on ``oauth_tokens`` — one row per user per
   platform, spanning every account in ``accessible_accounts``. One ingest key per
   login means an agency's client A posts conversions into whichever dataset was
   resolved last, possibly client B's, in client B's business portfolio. Billing is
   per ad account (``uq_user_ad_account_sub``); tracking has to match.

2. ``2d9b4cd8c567`` was autogenerated against a database that carried those columns
   while its models did not, so it emitted four ``drop_column`` calls against
   ``oauth_tokens``. On a fresh database the drop runs before anything creates
   them, so ``alembic upgrade head`` failed for every new developer and every CI
   run.
"""
from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import pytest

from app.core.config import settings
from app.modules.ads.models import AdsAccount, OAuthToken
from app.modules.tracking.schemas import TrackingEventBatch
from app.modules.tracking.service import TrackingError, TrackingService

TRACKING_COLUMNS = {
    "tracking_dataset_id",
    "tracking_business_id",
    "tracking_ingest_key",
    "tracking_system_user_token",
}


def test_tracking_state_lives_on_the_ad_account():
    assert TRACKING_COLUMNS <= set(AdsAccount.__table__.columns.keys())
    assert TRACKING_COLUMNS.isdisjoint(OAuthToken.__table__.columns.keys())


def test_one_row_per_account_is_enforced_by_the_database():
    """``get_tracking_account`` creates on demand, read-then-insert. The same race
    produced duplicate ``oauth_tokens`` rows and a permanent "not connected"."""
    assert any(
        sorted(c.name for c in constraint.columns) == ["ad_account_id", "oauth_token_id"]
        for constraint in AdsAccount.__table__.constraints
        if hasattr(constraint, "columns") and constraint.__class__.__name__ == "UniqueConstraint"
    )


def test_no_migration_drops_the_tracking_columns():
    versions = Path(__file__).resolve().parents[1] / "alembic" / "versions"
    offenders = [
        path.name
        for path in versions.glob("*.py")
        for column in TRACKING_COLUMNS
        if f"drop_column('oauth_tokens', '{column}')" in path.read_text(encoding="utf-8")
    ]
    assert not offenders, f"unguarded drop of tracking columns in {offenders}"


class _StubRepo:
    """Only what TrackingService.send touches."""

    def __init__(self, key: str, dataset_id: str):
        self.account = SimpleNamespace(
            user_id="user-1",
            tracking_ingest_key=key,
            tracking_dataset_id=dataset_id,
            tracking_system_user_token=None,
            # Null is the real default and reads as "the full pixel + server
            # setup", so the ingest gate lets it through. These tests are about
            # which DATASET a batch lands in, not about the gate.
            tracking_method=None,
            oauth_token=SimpleNamespace(access_token="token", is_valid=True),
        )

    async def get_account_by_ingest_key(self, db, ingest_key):
        return self.account if ingest_key == self.account.tracking_ingest_key else None


def _batch(**kwargs) -> TrackingEventBatch:
    return TrackingEventBatch(
        events=[{"event_name": "Purchase", "email": "buyer@example.com"}], **kwargs
    )


async def _send(monkeypatch, batch) -> str:
    """Run one batch, return the dataset id it was reported against."""
    sent: dict = {}

    async def _capture(dataset_id, events, *, access_token, test_event_code=None):
        sent["dataset_id"] = dataset_id
        return {"events_received": len(events), "errors": []}

    monkeypatch.setattr(settings, "CAPI_ENABLED", True)
    monkeypatch.setattr("app.services.meta_capi.send_events", _capture)
    service = TrackingService(_StubRepo("key-a", "dataset-default"))
    await service.send(
        None, ingest_key="key-a", batch=batch, client_ip="", user_agent="",
    )
    return sent["dataset_id"]


@pytest.mark.asyncio
async def test_batch_defaults_to_the_accounts_remembered_dataset(monkeypatch):
    assert await _send(monkeypatch, _batch()) == "dataset-default"


@pytest.mark.asyncio
async def test_batch_can_name_a_dataset_when_the_account_has_several(monkeypatch):
    """One ad account, two websites, two datasets: sending both sites' conversions
    to the default deduplicates against the wrong pixel."""
    assert await _send(monkeypatch, _batch(dataset_id="dataset-second-site")) == "dataset-second-site"


@pytest.mark.asyncio
async def test_another_tenants_key_resolves_to_nothing():
    service = TrackingService(_StubRepo("key-a", "dataset-default"))
    with pytest.raises(TrackingError) as excinfo:
        await service.account_for_key(None, "key-b")
    assert excinfo.value.status_code == 401
