"""added is_payment_done

Revision ID: a4207280dac6
Revises: b554c27a5586
Create Date: 2026-08-23 15:59:09.906610+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4207280dac6'
down_revision: Union[str, None] = 'b554c27a5586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('early_access_payments', sa.Column('is_payment_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('early_access_payments', 'is_payment_done')
    # ### end Alembic commands ###
