"""create_redeem_codes_and_redemptions_tables

Revision ID: 22eb57038ee5
Revises: a7f3c9e21d84
Create Date: 2026-09-09 17:30:53.594720+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22eb57038ee5'
down_revision: Union[str, None] = 'a7f3c9e21d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redeem_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_single', sa.Boolean(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=False),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redeem_codes_code'), 'redeem_codes', ['code'], unique=True)
    op.create_index(op.f('ix_redeem_codes_created_by'), 'redeem_codes', ['created_by'], unique=False)
    op.create_table('redeem_code_redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('redeem_code_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['redeem_code_id'], ['redeem_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redeem_code_redemptions_redeem_code_id'), 'redeem_code_redemptions', ['redeem_code_id'], unique=False)
    op.create_index(op.f('ix_redeem_code_redemptions_user_id'), 'redeem_code_redemptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redeem_code_redemptions_user_id'), table_name='redeem_code_redemptions')
    op.drop_index(op.f('ix_redeem_code_redemptions_redeem_code_id'), table_name='redeem_code_redemptions')
    op.drop_table('redeem_code_redemptions')
    op.drop_index(op.f('ix_redeem_codes_created_by'), table_name='redeem_codes')
    op.drop_index(op.f('ix_redeem_codes_code'), table_name='redeem_codes')
    op.drop_table('redeem_codes')
    # ### end Alembic commands ###
