"""subscription model  added new field

Revision ID: 12d8509f46ae
Revises: 627088b269ab
Create Date: 2026-08-23 13:59:44.115533+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d8509f46ae'
down_revision: Union[str, None] = '627088b269ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'slug')
    op.drop_column('subscriptions', 'name')
    # ### end Alembic commands ###
