"""create early access payment model and businessname field added in user

Revision ID: 0cc3e4ef3690
Revises: 4ef5364eb961
Create Date: 2026-08-23 13:45:20.100514+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc3e4ef3690'
down_revision: Union[str, None] = '4ef5364eb961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('early_access_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_early_access_payments_email'), 'early_access_payments', ['email'], unique=False)
    op.create_index(op.f('ix_ads_accounts_tracking_lead_page_id'), 'ads_accounts', ['tracking_lead_page_id'], unique=False)
    op.alter_column('chat_messages', 'checkpoint_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('users', sa.Column('business_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_name')
    op.alter_column('chat_messages', 'checkpoint_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_ads_accounts_tracking_lead_page_id'), table_name='ads_accounts')
    op.drop_index(op.f('ix_early_access_payments_email'), table_name='early_access_payments')
    op.drop_table('early_access_payments')
    # ### end Alembic commands ###
