"""added new field why choose punk field

Revision ID: 627088b269ab
Revises: 0cc3e4ef3690
Create Date: 2026-08-23 13:48:42.964398+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627088b269ab'
down_revision: Union[str, None] = '0cc3e4ef3690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('early_access_payments', sa.Column('why_choose_punk', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('early_access_payments', 'why_choose_punk')
    # ### end Alembic commands ###
