"""subscription model  added new field

Revision ID: b485188119cf
Revises: 12d8509f46ae
Create Date: 2026-08-23 14:03:38.767647+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b485188119cf'
down_revision: Union[str, None] = '12d8509f46ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('interval', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'interval')
    # ### end Alembic commands ###
