"""add phone column to users

Revision ID: f8cc30cf037e
Revises: c4d8a1f3e207
Create Date: 2026-08-19 04:20:54.114095+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cc30cf037e'
down_revision: Union[str, None] = 'c4d8a1f3e207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ads_accounts_tracking_ingest_key', table_name='ads_accounts', postgresql_where='(tracking_ingest_key IS NOT NULL)')
    op.drop_index('uq_ads_accounts_token_account', table_name='ads_accounts')
    op.create_unique_constraint('uq_ads_accounts_token_account', 'ads_accounts', ['oauth_token_id', 'ad_account_id'])
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_constraint('uq_ads_accounts_token_account', 'ads_accounts', type_='unique')
    op.create_index('uq_ads_accounts_token_account', 'ads_accounts', ['oauth_token_id', 'ad_account_id'], unique=True)
    op.create_index('uq_ads_accounts_tracking_ingest_key', 'ads_accounts', ['tracking_ingest_key'], unique=True, postgresql_where='(tracking_ingest_key IS NOT NULL)')
    # ### end Alembic commands ###
