"""create legal_documents table

Revision ID: 9d502ba45a7f
Revises: c1a2b3d4e5f6
Create Date: 2026-09-05 15:42:59.528285+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d502ba45a7f'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('TERMS_OF_SERVICE', 'PRIVACY_POLICY', name='documenttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Float(), nullable=False),
    sa.Column('language', sa.Enum('ENGLISH', 'FRANCE', name='documentlanguage'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_documents')
    # ### end Alembic commands ###
