"""Add faq and support modules

Revision ID: b814d46712fb
Revises: 56936687c5af
Create Date: 2026-08-29 06:34:28.148696+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b814d46712fb'
down_revision: Union[str, None] = '56936687c5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('faq', 'support', 'both', name='faqcategorytype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_categories_is_active'), 'faq_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_faq_categories_name'), 'faq_categories', ['name'], unique=True)
    op.create_table('faqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['faq_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_category_id'), 'faqs', ['category_id'], unique=False)
    op.create_index(op.f('ix_faqs_is_active'), 'faqs', ['is_active'], unique=False)
    op.create_table('supports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('problem_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='supportstatus'), nullable=False),
    sa.Column('attachment', sa.String(length=1024), nullable=True),
    sa.Column('attachment_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['faq_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supports_category_id'), 'supports', ['category_id'], unique=False)
    op.create_index(op.f('ix_supports_user_id'), 'supports', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate diffed this branch against a stale `models.py` that
    # predated 56936687c5af (this migration's own `down_revision`) and wrongly
    # proposed dropping `maid_extractions.audience_filter` /
    # `filtered_maid_count` — columns this migration has no business touching.
    # Removed; see a93a65af1cb4_restore_maid_extraction_audience_columns.py
    # for the follow-up that puts them back on any DB where this already ran.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supports_user_id'), table_name='supports')
    op.drop_index(op.f('ix_supports_category_id'), table_name='supports')
    op.drop_table('supports')
    op.drop_index(op.f('ix_faqs_is_active'), table_name='faqs')
    op.drop_index(op.f('ix_faqs_category_id'), table_name='faqs')
    op.drop_table('faqs')
    op.drop_index(op.f('ix_faq_categories_name'), table_name='faq_categories')
    op.drop_index(op.f('ix_faq_categories_is_active'), table_name='faq_categories')
    op.drop_table('faq_categories')
    # ### end Alembic commands ###
