"""new field added in campaign page

Revision ID: 7c95fa3e6847
Revises: e6b2c4d8f031
Create Date: 2026-09-17 19:26:07.770523+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c95fa3e6847'
down_revision: Union[str, None] = 'e6b2c4d8f031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('meta_ads_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_campaigns_meta_ads_id'), 'campaigns', ['meta_ads_id'], unique=False)
    op.drop_constraint('faq_categories_name_key', 'faq_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('faq_categories_name_key', 'faq_categories', ['name'])
    op.drop_index(op.f('ix_campaigns_meta_ads_id'), table_name='campaigns')
    op.drop_column('campaigns', 'meta_ads_id')
    # ### end Alembic commands ###
