"""conversion event log + the account's optimized event

Two things, both about the CAPI event *name* rather than the dataset:

  ads_accounts.tracking_event_type   which conversion the account's campaigns
                                     optimize toward, in Meta's custom_event_type
                                     spelling ("LEAD"). Remembered so the tracking
                                     card hands out a snippet firing the SAME event
                                     the ad set is learning from — the fixed
                                     "Purchase" default installed the one event a
                                     Leads campaign does not use, and a dataset
                                     receiving everything except the optimized
                                     event reads as working tracking

  tracking_events                    one row per conversion Punk forwarded, with
                                     Meta's verdict. Before it, ``send`` reported
                                     and forgot, so "we never received it" and
                                     "Meta rejected it" were the same silence when
                                     an advertiser asked why conversions were
                                     missing

The log stores NO identifiers — not email/phone/name, not their hashes. meta_capi
normalizes and SHA-256s those on the way out and keeps no copy; a record of who
converted would be a second store of the advertiser's customers' PII, sitting
behind an ingest key that lives in a public website snippet's server half.

``IF NOT EXISTS`` on every statement and hand-written rather than autogenerated,
for the reason ``a3f1c07b95de`` documents.

``ads_account_id`` is the tenant boundary and matches where the ingest key lives:
one login reaches several ad accounts, and an agency must not read one client's
conversions from another client's screen.

Revision ID: b7c2e6d41a8f
Revises: a3f1c07b95de
Create Date: 2026-08-19 09:00:00.000000+00:00
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7c2e6d41a8f'
down_revision: Union[str, None] = 'a3f1c07b95de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE ads_accounts "
        "ADD COLUMN IF NOT EXISTS tracking_event_type VARCHAR(50)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS tracking_events (
            id UUID PRIMARY KEY,
            ads_account_id UUID NOT NULL
                REFERENCES ads_accounts (id) ON DELETE CASCADE,
            dataset_id VARCHAR(100) NOT NULL,
            event_name VARCHAR(100) NOT NULL,
            event_id VARCHAR(100),
            action_source VARCHAR(40),
            value NUMERIC(18, 4),
            currency VARCHAR(3),
            events_received INTEGER NOT NULL DEFAULT 0,
            error TEXT,
            created_at TIMESTAMPTZ DEFAULT now()
        )
        """
    )
    # Every read is "the latest N for this account" — without this the scan grows
    # with every conversion the advertiser has ever made. Ascending: Postgres
    # walks a btree backwards just as cheaply, and a DESC index here would read as
    # drift against the model on every ``alembic check``.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tracking_events_account_created "
        "ON tracking_events (ads_account_id, created_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tracking_events_ads_account_id "
        "ON tracking_events (ads_account_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_tracking_events_created_at "
        "ON tracking_events (created_at)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS tracking_events")
    # tracking_event_type stays for the same reason a3f1c07b95de keeps its
    # columns: it is what the live snippet on the advertiser's site was generated
    # from, and re-deriving it needs a campaign rebuild.
