"""autorenwal field added in usersubscription

Revision ID: 4ef5364eb961
Revises: 95e8c4629709
Create Date: 2026-08-22 04:46:05.111810+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef5364eb961'
down_revision: Union[str, None] = '95e8c4629709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ads_accounts_tracking_lead_page_id', table_name='ads_accounts', postgresql_where='(tracking_lead_page_id IS NOT NULL)')
    op.alter_column('chat_messages', 'checkpoint_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('user_subscriptions', sa.Column('auto_renewal', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_subscriptions SET auto_renewal = TRUE")
    op.alter_column('user_subscriptions', 'auto_renewal', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'auto_renewal')
    op.alter_column('chat_messages', 'checkpoint_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index('ix_ads_accounts_tracking_lead_page_id', 'ads_accounts', ['tracking_lead_page_id'], unique=False, postgresql_where='(tracking_lead_page_id IS NOT NULL)')
    # ### end Alembic commands ###
