"""alembic generate

Revision ID: 832ec00ed47c
Revises: 
Create Date: 2026-08-18 20:25:01.184846+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '832ec00ed47c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracking_events_account_created', table_name='tracking_events')
    op.drop_index('ix_tracking_events_ads_account_id', table_name='tracking_events')
    op.drop_index('ix_tracking_events_created_at', table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index('uq_ads_accounts_token_account', table_name='ads_accounts')
    op.drop_index('uq_ads_accounts_tracking_ingest_key', table_name='ads_accounts', postgresql_where='(tracking_ingest_key IS NOT NULL)')
    op.drop_column('ads_accounts', 'tracking_ingest_key')
    op.drop_column('ads_accounts', 'tracking_dataset_id')
    op.drop_column('ads_accounts', 'tracking_event_type')
    op.drop_column('ads_accounts', 'tracking_business_id')
    op.drop_column('ads_accounts', 'tracking_system_user_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads_accounts', sa.Column('tracking_system_user_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads_accounts', sa.Column('tracking_business_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ads_accounts', sa.Column('tracking_event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ads_accounts', sa.Column('tracking_dataset_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ads_accounts', sa.Column('tracking_ingest_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('uq_ads_accounts_tracking_ingest_key', 'ads_accounts', ['tracking_ingest_key'], unique=True, postgresql_where='(tracking_ingest_key IS NOT NULL)')
    op.create_index('uq_ads_accounts_token_account', 'ads_accounts', ['oauth_token_id', 'ad_account_id'], unique=True)
    op.create_table('tracking_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ads_account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('action_source', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('value', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('events_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ads_account_id'], ['ads_accounts.id'], name='tracking_events_ads_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tracking_events_pkey')
    )
    op.create_index('ix_tracking_events_created_at', 'tracking_events', ['created_at'], unique=False)
    op.create_index('ix_tracking_events_ads_account_id', 'tracking_events', ['ads_account_id'], unique=False)
    op.create_index('ix_tracking_events_account_created', 'tracking_events', ['ads_account_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
