"""add_subscription_linking_and_tokens

Revision ID: 95e8c4629709
Revises: a41b7c6d92e5
Create Date: 2026-08-21 12:58:18.442502+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e8c4629709'
down_revision: Union[str, None] = 'a41b7c6d92e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_ads_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('ads_account_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_ads_accounts_ads_account_id'), 'subscription_ads_accounts', ['ads_account_id'], unique=False)
    op.create_table('subscription_token_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_table('token_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('tx_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_transactions_user_id'), 'token_transactions', ['user_id'], unique=False)
    op.add_column('user_subscriptions', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user_subscriptions', sa.Column('normalized_email', sa.String(length=255), nullable=True))
    op.add_column('user_subscriptions', sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_subscriptions', sa.Column('used_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_subscriptions', sa.Column('remaining_tokens', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_user_subscriptions_normalized_email'), 'user_subscriptions', ['normalized_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscriptions_normalized_email'), table_name='user_subscriptions')
    op.drop_column('user_subscriptions', 'remaining_tokens')
    op.drop_column('user_subscriptions', 'used_tokens')
    op.drop_column('user_subscriptions', 'total_tokens')
    op.drop_column('user_subscriptions', 'normalized_email')
    op.drop_column('user_subscriptions', 'email')
    op.drop_index(op.f('ix_token_transactions_user_id'), table_name='token_transactions')
    op.drop_table('token_transactions')
    op.drop_table('subscription_token_allocations')
    op.drop_index(op.f('ix_subscription_ads_accounts_ads_account_id'), table_name='subscription_ads_accounts')
    op.drop_table('subscription_ads_accounts')
    # ### end Alembic commands ###
