"""update legal_documents unique constraint to doc_type and language

Revision ID: e223525beee9
Revises: 99b7ca62e919
Create Date: 2026-09-05 15:57:13.574701+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e223525beee9'
down_revision: Union[str, None] = '99b7ca62e919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('legal_documents_doc_type_key', 'legal_documents', type_='unique')
    op.create_unique_constraint('uq_legal_document_doc_type_language', 'legal_documents', ['doc_type', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_legal_document_doc_type_language', 'legal_documents', type_='unique')
    op.create_unique_constraint('legal_documents_doc_type_key', 'legal_documents', ['doc_type'])
    # ### end Alembic commands ###
