"""add relationship between user_subscription and subscription

Revision ID: ad4ddd6ddf40
Revises: f8cc30cf037e
Create Date: 2026-08-19 05:01:18.956064+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4ddd6ddf40'
down_revision: Union[str, None] = 'f8cc30cf037e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_price_id', table_name='subscriptions')
    op.alter_column('user_subscriptions', 'plan_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using="CASE WHEN plan_id ~ '^[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}$' THEN plan_id::uuid ELSE NULL END")
    op.create_foreign_key(None, 'user_subscriptions', 'subscriptions', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.alter_column('user_subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_index('ix_subscriptions_price_id', 'subscriptions', ['price_id'], unique=True)
    # ### end Alembic commands ###
