"""ads_accounts: per-ad-account conversion tracking columns

Conversion tracking (Meta Pixel/dataset + Conversions API) is resolved per
connected ad account, in the user's own Meta assets — Punk owns no dataset and
holds no platform-wide Meta credential. Four columns carry that state on the ad
account row, because the alternative is re-deriving it from Graph on every
session:

  tracking_dataset_id         which dataset this ad account publishes and sends
                              server events against, by default. Not a cap of
                              one: an account can see several datasets, the
                              campaign picker chooses per campaign, and this
                              remembers the last choice
  tracking_business_id        the business portfolio owning it, when the ad
                              account has one; null for personal accounts, where
                              the dataset lives on the ad account itself
  tracking_ingest_key         shared secret for POST /tracking/events, so the
                              customer's site or CRM can hand us conversions
                              without holding a Meta token
  tracking_system_user_token  OPTIONAL, encrypted. An advertiser who wants server
                              events to outlive an OAuth token pastes a system
                              user token from their own Business Settings

On ``ads_accounts`` rather than ``oauth_tokens``: one oauth_tokens row is one
login, and it spans every ad account in ``accessible_accounts``. Billing is per
ad account (``uq_user_ad_account_sub``), a dataset belongs to an ad account or a
business, and an ingest key is a tenant boundary — an agency running three client
accounts off one login must not have one key that writes every client's
conversions into whichever dataset was resolved last.

Why the state has to be remembered rather than recomputed: the dataset list comes
back from Graph in no guaranteed order, so a user who accepted one of several
could silently be switched to another on the next run — and a switched dataset
means the ad set optimizes toward an event store with none of the history.

``IF NOT EXISTS`` on every statement, and hand-written rather than autogenerated,
for the reason ``d9e4a17c85b3`` documents — and for the reason ``2d9b4cd8c567``
demonstrates.

``tracking_system_user_token`` is TEXT: ``EncryptedString`` stores a Fernet
ciphertext, which is far longer than the token it wraps and has no useful bound.

The four ``oauth_tokens`` columns are dropped here. They only ever existed on a
developer machine — this revision was never committed while it targeted that
table — so there is no tracking data to carry across.

Revises ``832ec00ed47c``, which is the whole of dev's migration history now.
``8439fc8b0a7a`` was this branch's head when the revision was written, then
``5886e701e04d`` once dev landed ``added_adsaccount_model`` →
``add_ads_accounts_table`` off the same parent; ``145805be`` then deleted all
seventeen version files and replaced them with one autogenerated baseline. Third
parent, third reason — which is why every statement below is ``IF NOT EXISTS``
rather than autogenerated. ``832ec00ed47c`` was itself autogenerated against a
database carrying this branch's tracking schema while dev's models did not, so it
*drops* the columns this revision adds; they are re-added here, in order, and the
end state is the one the models describe.

Revision ID: a3f1c07b95de
Revises: 832ec00ed47c
Create Date: 2026-08-17 12:00:00.000000+00:00
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a3f1c07b95de'
down_revision: Union[str, None] = '832ec00ed47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TABLE ads_accounts "
        "ADD COLUMN IF NOT EXISTS tracking_dataset_id VARCHAR(100)"
    )
    op.execute(
        "ALTER TABLE ads_accounts "
        "ADD COLUMN IF NOT EXISTS tracking_business_id VARCHAR(100)"
    )
    op.execute(
        "ALTER TABLE ads_accounts "
        "ADD COLUMN IF NOT EXISTS tracking_ingest_key VARCHAR(64)"
    )
    op.execute(
        "ALTER TABLE ads_accounts "
        "ADD COLUMN IF NOT EXISTS tracking_system_user_token TEXT"
    )

    # The ingest key identifies the tenant on the one route in Punk that an
    # outside machine calls unauthenticated. Unique makes a collision impossible
    # instead of unlikely, and indexes the lookup that route does on every batch.
    # Partial, because every account that has not set tracking up holds NULL.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_ads_accounts_tracking_ingest_key "
        "ON ads_accounts (tracking_ingest_key) "
        "WHERE tracking_ingest_key IS NOT NULL"
    )

    # The tracking reads get-or-create this row, which is the same read-then-insert
    # race that produced duplicate oauth_tokens rows and turned into a permanent
    # "not connected" for that user. Let the database settle it.
    op.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_ads_accounts_token_account "
        "ON ads_accounts (oauth_token_id, ad_account_id)"
    )

    for column in (
        "tracking_dataset_id",
        "tracking_business_id",
        "tracking_ingest_key",
        "tracking_system_user_token",
    ):
        op.execute(f"ALTER TABLE oauth_tokens DROP COLUMN IF EXISTS {column}")


def downgrade() -> None:
    # The ingest key is live in whatever snippet or CRM webhook the advertiser
    # already installed, and the dataset id is what published campaigns optimize
    # against. Dropping either on a downgrade breaks tracking that is running, so
    # going back one revision leaves the columns in place.
    pass
