"""restore maid extraction audience columns

Revision ID: a93a65af1cb4
Revises: b814d46712fb
Create Date: 2026-08-31 20:45:02.956566+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93a65af1cb4'
down_revision: Union[str, None] = 'b814d46712fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # b814d46712fb (this migration's own parent) autogenerated a drop of these
    # two columns against a stale `models.py` snapshot, undoing what
    # 56936687c5af had just added — see that migration for the removed lines.
    # `models.py` (app/db/models.py) never stopped declaring them, so every
    # ORM read/write against MaidExtraction has been targeting columns the DB
    # doesn't have since b814d46712fb landed. IF NOT EXISTS: idempotent on a
    # DB that runs this chain fresh (b814d46712fb no longer drops them, so
    # they're already present) and on one that already suffered the drop.
    op.execute(
        "ALTER TABLE maid_extractions ADD COLUMN IF NOT EXISTS audience_filter JSON"
    )
    op.execute(
        "ALTER TABLE maid_extractions ADD COLUMN IF NOT EXISTS filtered_maid_count INTEGER"
    )


def downgrade() -> None:
    op.drop_column('maid_extractions', 'filtered_maid_count')
    op.drop_column('maid_extractions', 'audience_filter')
