"""change legal_documents version to string

Revision ID: 0234adbd58ba
Revises: e223525beee9
Create Date: 2026-09-05 17:09:27.661444+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0234adbd58ba'
down_revision: Union[str, None] = 'e223525beee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legal_documents', 'version',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('legal_documents', 'version',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
