"""verify_split

Revision ID: 3801d9c9a16a
Revises: ad4ddd6ddf40
Create Date: 2026-08-19 05:31:16.004963+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3801d9c9a16a'
down_revision: Union[str, None] = 'ad4ddd6ddf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
