"""add type to subscription

Revision ID: e8ee3c9c127b
Revises: 7d3b145a901e
Create Date: 2026-09-24 10:25:45.040892+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ee3c9c127b'
down_revision: Union[str, None] = '7d3b145a901e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    purchasetype = sa.Enum('SUBSCRIPTION', 'TOKEN_PACK', name='purchasetype')
    purchasetype.create(op.get_bind(), checkfirst=True)
    op.add_column('subscriptions', sa.Column('type', purchasetype, nullable=True))
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_column('subscriptions', 'type')
    # ### end Alembic commands ###
