"""added new field in usersubscription model

Revision ID: 19a5439a450f
Revises: a4207280dac6
Create Date: 2026-08-25 04:13:16.798680+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a5439a450f'
down_revision: Union[str, None] = 'a4207280dac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum('active', 'trialing', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused', 'free', 'complete', name='subscriptionpaymentstatus')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user_subscriptions', sa.Column('payment_status', payment_status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'payment_status')
    payment_status_enum = sa.Enum('active', 'trialing', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused', 'free', 'complete', name='subscriptionpaymentstatus')
    payment_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
