/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardUsersIndexRouteImport } from './routes/(dashboard)/users/index'
import { Route as dashboardSubscriptionIndexRouteImport } from './routes/(dashboard)/subscription/index'
import { Route as dashboardProfileIndexRouteImport } from './routes/(dashboard)/profile/index'
import { Route as dashboardEventsIndexRouteImport } from './routes/(dashboard)/events/index'
import { Route as dashboardCampaignsIndexRouteImport } from './routes/(dashboard)/campaigns/index'
import { Route as dashboardAnalyticsIndexRouteImport } from './routes/(dashboard)/analytics/index'
import { Route as dashboardSupportLegalDocIndexRouteImport } from './routes/(dashboard)/support/legal-doc/index'
import { Route as dashboardSupportInquiryIndexRouteImport } from './routes/(dashboard)/support/inquiry/index'
import { Route as dashboardSupportFaqIndexRouteImport } from './routes/(dashboard)/support/faq/index'
import { Route as dashboardSupportRedeemIndexRouteImport } from './routes/(dashboard)/support/Redeem/index'

const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardUsersIndexRoute = dashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardSubscriptionIndexRoute =
  dashboardSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardProfileIndexRoute = dashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardEventsIndexRoute = dashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardCampaignsIndexRoute = dashboardCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardAnalyticsIndexRoute = dashboardAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardSupportLegalDocIndexRoute =
  dashboardSupportLegalDocIndexRouteImport.update({
    id: '/support/legal-doc/',
    path: '/support/legal-doc/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSupportInquiryIndexRoute =
  dashboardSupportInquiryIndexRouteImport.update({
    id: '/support/inquiry/',
    path: '/support/inquiry/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSupportFaqIndexRoute =
  dashboardSupportFaqIndexRouteImport.update({
    id: '/support/faq/',
    path: '/support/faq/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardSupportRedeemIndexRoute =
  dashboardSupportRedeemIndexRouteImport.update({
    id: '/support/Redeem/',
    path: '/support/Redeem/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof dashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/analytics/': typeof dashboardAnalyticsIndexRoute
  '/campaigns/': typeof dashboardCampaignsIndexRoute
  '/events/': typeof dashboardEventsIndexRoute
  '/profile/': typeof dashboardProfileIndexRoute
  '/subscription/': typeof dashboardSubscriptionIndexRoute
  '/users/': typeof dashboardUsersIndexRoute
  '/support/Redeem/': typeof dashboardSupportRedeemIndexRoute
  '/support/faq/': typeof dashboardSupportFaqIndexRoute
  '/support/inquiry/': typeof dashboardSupportInquiryIndexRoute
  '/support/legal-doc/': typeof dashboardSupportLegalDocIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/analytics': typeof dashboardAnalyticsIndexRoute
  '/campaigns': typeof dashboardCampaignsIndexRoute
  '/events': typeof dashboardEventsIndexRoute
  '/profile': typeof dashboardProfileIndexRoute
  '/subscription': typeof dashboardSubscriptionIndexRoute
  '/users': typeof dashboardUsersIndexRoute
  '/support/Redeem': typeof dashboardSupportRedeemIndexRoute
  '/support/faq': typeof dashboardSupportFaqIndexRoute
  '/support/inquiry': typeof dashboardSupportInquiryIndexRoute
  '/support/legal-doc': typeof dashboardSupportLegalDocIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(dashboard)/analytics/': typeof dashboardAnalyticsIndexRoute
  '/(dashboard)/campaigns/': typeof dashboardCampaignsIndexRoute
  '/(dashboard)/events/': typeof dashboardEventsIndexRoute
  '/(dashboard)/profile/': typeof dashboardProfileIndexRoute
  '/(dashboard)/subscription/': typeof dashboardSubscriptionIndexRoute
  '/(dashboard)/users/': typeof dashboardUsersIndexRoute
  '/(dashboard)/support/Redeem/': typeof dashboardSupportRedeemIndexRoute
  '/(dashboard)/support/faq/': typeof dashboardSupportFaqIndexRoute
  '/(dashboard)/support/inquiry/': typeof dashboardSupportInquiryIndexRoute
  '/(dashboard)/support/legal-doc/': typeof dashboardSupportLegalDocIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/analytics/'
    | '/campaigns/'
    | '/events/'
    | '/profile/'
    | '/subscription/'
    | '/users/'
    | '/support/Redeem/'
    | '/support/faq/'
    | '/support/inquiry/'
    | '/support/legal-doc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/campaigns'
    | '/events'
    | '/profile'
    | '/subscription'
    | '/users'
    | '/support/Redeem'
    | '/support/faq'
    | '/support/inquiry'
    | '/support/legal-doc'
  id:
    | '__root__'
    | '/(dashboard)'
    | '/(dashboard)/'
    | '/login/'
    | '/(dashboard)/analytics/'
    | '/(dashboard)/campaigns/'
    | '/(dashboard)/events/'
    | '/(dashboard)/profile/'
    | '/(dashboard)/subscription/'
    | '/(dashboard)/users/'
    | '/(dashboard)/support/Redeem/'
    | '/(dashboard)/support/faq/'
    | '/(dashboard)/support/inquiry/'
    | '/(dashboard)/support/legal-doc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/users/': {
      id: '/(dashboard)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof dashboardUsersIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/subscription/': {
      id: '/(dashboard)/subscription/'
      path: '/subscription'
      fullPath: '/subscription/'
      preLoaderRoute: typeof dashboardSubscriptionIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/profile/': {
      id: '/(dashboard)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof dashboardProfileIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/events/': {
      id: '/(dashboard)/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof dashboardEventsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/campaigns/': {
      id: '/(dashboard)/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof dashboardCampaignsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/analytics/': {
      id: '/(dashboard)/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof dashboardAnalyticsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/support/legal-doc/': {
      id: '/(dashboard)/support/legal-doc/'
      path: '/support/legal-doc'
      fullPath: '/support/legal-doc/'
      preLoaderRoute: typeof dashboardSupportLegalDocIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/support/inquiry/': {
      id: '/(dashboard)/support/inquiry/'
      path: '/support/inquiry'
      fullPath: '/support/inquiry/'
      preLoaderRoute: typeof dashboardSupportInquiryIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/support/faq/': {
      id: '/(dashboard)/support/faq/'
      path: '/support/faq'
      fullPath: '/support/faq/'
      preLoaderRoute: typeof dashboardSupportFaqIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/support/Redeem/': {
      id: '/(dashboard)/support/Redeem/'
      path: '/support/Redeem'
      fullPath: '/support/Redeem/'
      preLoaderRoute: typeof dashboardSupportRedeemIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardAnalyticsIndexRoute: typeof dashboardAnalyticsIndexRoute
  dashboardCampaignsIndexRoute: typeof dashboardCampaignsIndexRoute
  dashboardEventsIndexRoute: typeof dashboardEventsIndexRoute
  dashboardProfileIndexRoute: typeof dashboardProfileIndexRoute
  dashboardSubscriptionIndexRoute: typeof dashboardSubscriptionIndexRoute
  dashboardUsersIndexRoute: typeof dashboardUsersIndexRoute
  dashboardSupportRedeemIndexRoute: typeof dashboardSupportRedeemIndexRoute
  dashboardSupportFaqIndexRoute: typeof dashboardSupportFaqIndexRoute
  dashboardSupportInquiryIndexRoute: typeof dashboardSupportInquiryIndexRoute
  dashboardSupportLegalDocIndexRoute: typeof dashboardSupportLegalDocIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardAnalyticsIndexRoute: dashboardAnalyticsIndexRoute,
  dashboardCampaignsIndexRoute: dashboardCampaignsIndexRoute,
  dashboardEventsIndexRoute: dashboardEventsIndexRoute,
  dashboardProfileIndexRoute: dashboardProfileIndexRoute,
  dashboardSubscriptionIndexRoute: dashboardSubscriptionIndexRoute,
  dashboardUsersIndexRoute: dashboardUsersIndexRoute,
  dashboardSupportRedeemIndexRoute: dashboardSupportRedeemIndexRoute,
  dashboardSupportFaqIndexRoute: dashboardSupportFaqIndexRoute,
  dashboardSupportInquiryIndexRoute: dashboardSupportInquiryIndexRoute,
  dashboardSupportLegalDocIndexRoute: dashboardSupportLegalDocIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
